import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import Navigation from '../components/Navigation';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { Button } from '../components/ui';
import { generateInvoicePDF } from '../utils/pdfGenerator';
import EditInvoiceModal from '../components/EditInvoiceModal';
import type { EditInvoiceData } from '../components/EditInvoiceModal';
import AddInvoiceItemModal from '../components/AddInvoiceItemModal';
import type { AddInvoiceItemData } from '../components/AddInvoiceItemModal';
import EditInvoiceItemModal from '../components/EditInvoiceItemModal';
import { useInvoice } from '../hooks/useInvoice';
import { useInvoices } from '../hooks/useInvoices';

const CreateInvoice: React.FC = () => {
  const { invoiceData, calculateTotals, updateDetails, addItem, removeItem, updateItem, reset } = useInvoice();
  const { saveInvoiceToFirebase, refetch } = useInvoices();
  const navigate = useNavigate();

  // Modal state
  const [isEditModalOpen, setIsEditModalOpen] = useState(false);
  const [isAddItemModalOpen, setIsAddItemModalOpen] = useState(false);
  const [isEditItemModalOpen, setIsEditItemModalOpen] = useState(false);
  const [selectedItemForEdit, setSelectedItemForEdit] = useState<AddInvoiceItemData | null>(null);
  const [isGeneratingInvoice, setIsGeneratingInvoice] = useState(false);

  const handleEditInvoice = () => {
    setIsEditModalOpen(true);
  };

  const handleCloseEditModal = () => {
    setIsEditModalOpen(false);
  };

  const handleAddItem = () => {
    setIsAddItemModalOpen(true);
  };

  const handleCloseAddItemModal = () => {
    setIsAddItemModalOpen(false);
  };

  const handleSaveAddItemModal = (data: AddInvoiceItemData) => {
    console.log('Adding invoice item:', data);
    // Add the new item to Redux
    addItem({
      particular: data.particular,
      jodi: data.jodi,
      box: data.box,
      jodiTotal: data.jodiTotal,
      rate: data.rate,
      amount: data.amount,
      no: '' // This will be auto-generated by the Redux slice
    });
  };

  const handleDeleteItem = (id: number) => {
    removeItem(id);
  };

  const handleEditItem = (item: any) => {
    setSelectedItemForEdit({
      particular: item.particular,
      jodi: item.jodi,
      box: item.box,
      jodiTotal: item.jodiTotal,
      rate: item.rate,
      amount: item.amount
    });
    setIsEditItemModalOpen(true);
  };

  const handleCloseEditItemModal = () => {
    setIsEditItemModalOpen(false);
    setSelectedItemForEdit(null);
  };

  const handleSaveEditItemModal = (data: AddInvoiceItemData) => {
    if (selectedItemForEdit) {
      // Find the item by matching the data
      const itemToUpdate = invoiceData.items.find(item => 
        item.particular === selectedItemForEdit.particular &&
        item.jodi === selectedItemForEdit.jodi &&
        item.box === selectedItemForEdit.box &&
        item.rate === selectedItemForEdit.rate
      );
      
      if (itemToUpdate) {
        updateItem(itemToUpdate.id, {
          particular: data.particular,
          jodi: data.jodi,
          box: data.box,
          jodiTotal: data.jodiTotal,
          rate: data.rate,
          amount: data.amount
        });
      }
    }
  };

  useEffect(() => {
    if(!invoiceData.businessName){
      handleEditInvoice();
    }
  }, []);

  const handleSaveEditModal = (data: EditInvoiceData) => {
    console.log('Saving invoice data:', data);
    // Update invoice details in Redux
    updateDetails({
      businessName: data.business,
      customer: data.customer,
      invoiceNo: data.invoiceNumber,
      invoiceDate: (() => {
        // Convert YYYY-MM-DD to DD-MM-YYYY format
        const [year, month, day] = data.date.split('-');
        return `${day}-${month}-${year}`;
      })()
    });
    setIsEditModalOpen(false);
  };

  const totals = calculateTotals();

  const handleGenerateInvoice = async () => {
    if (isGeneratingInvoice) return; // Prevent multiple clicks
    
    setIsGeneratingInvoice(true);
    try {
      // First save the invoice to Firebase using Redux
      const success = await saveInvoiceToFirebase(invoiceData);
      if (success) {
        console.log('Invoice saved to Firebase successfully');
        
        // Fetch invoices again to refresh the data
        refetch();
        
        // Then generate the PDF
        await generateInvoicePDF(`invoice-${invoiceData.invoiceNo}-${invoiceData.invoiceDate}.pdf`);
        
        // You can add a success toast notification here
        console.log('Invoice saved and PDF generated successfully');
        
        // Reset the invoice slice after successful save and print
        reset();
        
        // Redirect to invoices page after successful save and print
        navigate('/invoice');
      } else {
        console.error('Failed to save invoice to Firebase');
      }
    } catch (error) {
      console.error('Failed to save invoice or generate PDF:', error);
      // You can add an error toast notification here
    } finally {
      setIsGeneratingInvoice(false);
    }
  };

  return (
    <div className="min-h-screen bg-white">
      <Navigation />
      <div style={{paddingBottom: '50px'}}>
      <div className=" py-xl print-this pb-20">
        {/* Invoice Form */}
        <div>
          {/* Invoice Header */}
                      <div className="text-center mb-xl">
              <div className="text-lg text-red-900 mb-sm">શ્રી ગણેશાય નમઃ</div>
            <h2 className="text-2xl font-bold mb-lg text-gray-800" >{invoiceData.businessName}</h2>
          </div>

          {/* Client and Invoice Information Table */}
          <div className="mb-lg">
            <table className="w-full border-collapse border border-blue-300 invoice-detail-table">
              <tbody>
                                 <tr>
                   <td style={{ width : "36%"}} className="border border-blue-300 px-md py-sm text-sm text-gray-700 font-medium w-56 left-top-align" colSpan={2} rowSpan={2}>{`M/S. : ${invoiceData.customer}`}</td>
                  <td className="border border-blue-300 px-md py-sm text-sm text-gray-700 font-medium w-22"><span className='number-span-bold'>Invoice No.:</span></td>
                  <td className="border border-blue-300 px-md py-sm text-sm text-gray-700 w-22"><span className='number-span-bold'>{invoiceData.invoiceNo}</span></td>
                </tr>
                <tr>
                  <td className="border border-blue-300 px-md py-sm text-sm text-gray-700 font-medium"><span className='number-span-bold'>Invoice Date:</span></td>
                  <td className="border border-blue-300 px-md py-sm text-sm text-gray-700" colSpan={1}><span className='number-span-bold'>{invoiceData.invoiceDate}</span></td>
                </tr>
              </tbody>
            </table>
          </div>

          {/* Invoice Table */}
          <div className="overflow-x-auto">
            <table className="w-full border-collapse border border-blue-300 invoice-table">
              <thead>
                <tr className="bg-blue-50">
                  <th className="border border-blue-300 px-md py-sm text-sm font-medium text-gray-700">No.</th>
                  <th className="border border-blue-300 px-md py-sm text-sm font-medium text-gray-700">Particular</th>
                  <th className="border border-blue-300 px-md py-sm text-sm font-medium text-gray-700">Jodi</th>
                  <th className="border border-blue-300 px-md py-sm text-sm font-medium text-gray-700">Box</th>
                  <th className="border border-blue-300 px-md py-sm text-sm font-medium text-gray-700">Jodi Total</th>
                  <th className="border border-blue-300 px-md py-sm text-sm font-medium text-gray-700">Rate</th>
                  <th className="border border-blue-300 px-md py-sm text-sm font-medium text-gray-700 border-right-none">Amount</th>
                  <th className="border border-blue-300 px-md py-sm text-sm font-medium text-gray-700 print-hide">Action</th>
                </tr>
              </thead>
              <tbody>
                {invoiceData.items.map((item) => (
                  // eslint-disable-next-line @typescript-eslint/no-unused-vars
                  <tr key={item.id} className="hover:bg-gray-50">
                    <td className="border border-blue-300 px-md py-sm text-sm text-gray-700"><span className='number-span'>{item.no}</span></td>
                    <td className="border border-blue-300 px-md py-sm text-sm text-gray-700"><span className='number-span'>{item.particular}</span></td>
                    <td className="border border-blue-300 px-md py-sm text-sm text-gray-700"><span className='number-span'>{item.jodi}</span></td>
                    <td className="border border-blue-300 px-md py-sm text-sm text-gray-700"><span className='number-span'>{item.box}</span></td>
                    <td className="border border-blue-300 px-md py-sm text-sm text-gray-700"><span className='number-span'>{item.jodiTotal}</span></td>
                    <td className="border border-blue-300 px-md py-sm text-sm text-gray-700"><span className='number-span'>{item.rate}</span></td>
                    <td className="border border-blue-300 px-md py-sm text-sm text-gray-700 border-right-none"><span className='number-span'>{item.amount}</span></td>
                    <td className="border border-blue-300 px-md py-sm text-sm text-gray-700 print-hide">
                      <div className="flex gap-sm">
                        <button
                          onClick={() => handleEditItem(item)}
                          className="text-blue-600 hover:text-blue-800 transition-colors p-1"
                          title="Edit item"
                        >
                          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                          </svg>
                        </button>
                        <button
                          onClick={() => handleDeleteItem(item.id)}
                          className="text-red-600 hover:text-red-800 transition-colors p-1"
                          title="Delete item"
                        >
                          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                          </svg>
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
                {/* Totals Row */}
                <tr className="bg-gray-50">
                  <td className="border border-blue-300 px-md text-sm text-gray-700"></td>
                  <td className="border border-blue-300 px-md text-sm text-gray-700"></td>
                  <td className="border border-blue-300 px-md text-sm text-gray-700"></td>
                  <td className="border border-blue-300 px-md text-sm text-gray-700">{totals.box}</td>
                  <td className="border border-blue-300 px-md text-sm text-gray-700">{totals.jodiTotal}</td>
                  <td className="border border-blue-300 px-md text-sm text-gray-700"></td>
                  <td className="border border-blue-300 px-md text-sm text-gray-700 border-right-none">{totals.amount}</td>
                  <td className="border border-blue-300 px-md text-sm text-gray-700 print-hide"></td>
                </tr>

                <tr className="bg-gray-50 font-bold">
                  <td className="border border-blue-300 px-md py-sm text-lg text-gray-700" colSpan={4}>Grand Total</td>
                  <td className="border border-blue-300 px-md py-sm text-lg text-gray-700" colSpan={3}>{totals.amount}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      </div>
      {/* Generate Invoice Button - Sticky at bottom */}
      <div className="fixed bottom-0 left-0 right-0 flex justify-between items-center px-xs py-lg" style={{ background: 'linear-gradient(to bottom, transparent, white)' }}>
        <div className="flex gap-sm">
                     <Button 
             variant="gradient" 
             size="md" 
             className="rounded-full w-12 h-12 p-0 flex items-center justify-center !border-radius-50"
             style={{ borderRadius: '50%' }}
             onClick={handleAddItem}
           >
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
            </svg>
          </Button>
          <Button 
            variant="gradient" 
            size="md" 
            className="rounded-full w-12 h-12 p-0 flex items-center justify-center !border-radius-50"
            style={{ borderRadius: '50%' }}
            onClick={handleEditInvoice}
          >
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
            </svg>
          </Button>
        </div>
        <Button 
          variant="gradient" 
          size="md" 
          onClick={handleGenerateInvoice}
          disabled={isGeneratingInvoice}
        >
          {isGeneratingInvoice ? 'Saving & Printing...' : 'Print'}
        </Button>
      </div>

             {/* Edit Invoice Modal */}
       <EditInvoiceModal
         isOpen={isEditModalOpen}
         onClose={handleCloseEditModal}
         onSave={handleSaveEditModal}
         initialData={{
           business: '',
           customer: '',
           invoiceNumber: invoiceData.invoiceNo,
           date: (() => {
             // Convert DD-MM-YYYY to YYYY-MM-DD format
             const [day, month, year] = invoiceData.invoiceDate.split('-');
             return `${year}-${month?.padStart(2, '0')}-${day?.padStart(2, '0')}`;
           })()
         }}
       />

       {/* Add Invoice Item Modal */}
              <AddInvoiceItemModal
         isOpen={isAddItemModalOpen}
         onClose={handleCloseAddItemModal}
         onSave={handleSaveAddItemModal}
       />

       {/* Edit Invoice Item Modal */}
       <EditInvoiceItemModal
         isOpen={isEditItemModalOpen}
         onClose={handleCloseEditItemModal}
         onSave={handleSaveEditItemModal}
         initialData={selectedItemForEdit || {
           particular: '',
           jodi: 0,
           box: 0,
           jodiTotal: 0,
           rate: 0,
           amount: 0
         }}
       />
     </div>
   );
 };
 
 export default CreateInvoice; 